# Generated by Django 3.1.3 on 2020-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
                ('freq', models.CharField(choices=[('Sóng m', 'Sóng m'), ('Sóng dm', 'Sóng dm'), ('Sóng cm', 'Sóng cm')], max_length=200, null=True)),
                ('display', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
