# Generated by Django 3.1.3 on 2020-12-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.content')),
                ('radar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.radar')),
            ],
        ),
        migrations.CreateModel(
            name='ContentB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.content')),
                ('contentA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.contenta')),
                ('radar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.radar')),
            ],
        ),
    ]
