# Generated by Django 3.1.3 on 2020-12-11 08:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_contenta_contentb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentb',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
