# Generated by Django 3.0.6 on 2020-05-27 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 15, 4, 58, 582022)),
        ),
    ]
