# Generated by Django 3.0.6 on 2020-05-27 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formNews', '0002_auto_20200527_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 22, 8, 27, 152844)),
        ),
    ]
