# Generated by Django 3.0.6 on 2020-05-31 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formNews', '0006_auto_20200531_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 21, 29, 26, 451997)),
        ),
    ]
