# Generated by Django 3.0.6 on 2020-05-31 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formNews', '0007_auto_20200531_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 22, 0, 13, 314930)),
        ),
    ]
